server:
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update   #create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


